spring:
  devtools:
    livereload:
      enabled: false
  h2:
    console:
      enabled: false
      
jwt:
  secret: # refresh token
  access: # access token
  refresh-expiredTime: # refresh token time
  acess-expiredTime: # access token time