# 스프링부트의 자동 설정과 관련된 정보 콘솔 출력기능
#debug: true
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
    # 사용법 : h2:file:{위치}/{db명}, h2:mem:{db명}. 테이블 저장을 위해 파일형태로 함
    url: jdbc:h2:file:D:/kyu-lab/h2/userdb # 파일로 사용중
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password: 1234
  h2:
    console:
      enabled: true
      path: /h2-user
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update

# 필요에 따라 로깅 레벨 변경
logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.apache.kafka.clients.consumer.ConsumerConfig: ERROR
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /docs-local
    groups:
      enabled: true
  swagger-ui:
    path: /swagger
    groups-order: asc
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true