spring:
  jackson:
    time-zone: Asia/Seoul
  devtools:
    livereload:
      enabled: true
  datasource:
    url: jdbc:postgresql://localhost:5432/kyulab
    driver-class-name: org.postgresql.Driver
    hikari:
      username: postgres
      password: 1234
  h2:
    console:
      enabled: false
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.hibernate.sql: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE
    org.apache.kafka.clients.consumer.ConsumerConfig: ERROR
    org.springframework.security: DEBUG
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG

jwt:
  secret: 64KY64qU7LWc6rec64+Z7J206rOg7J206rG07JWU7Zi47J206rOgIUDsnbTqsbTrrZDrg5A/JQ==
  refresh-expiredTime: 2592000 # 30일
  acess-expiredTime: 3600 # 1시간

springdoc:
  api-docs:
    path: /docs-user
    groups:
      enabled: true
  swagger-ui:
    path: /swagger
    groups-order: asc
    doc-expansion: none
    try-it-out-enabled: true
  cache:
    disabled: true
  model-and-view-allowed: true