spring:
  datasource:
    url: jdbc:h2:mem:userdb
    driver-class-name: org.h2.Driver
    hikari:
      username: sa
      password: 1234
  h2:
    console:
      enabled: true
      path: /h2-user
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        ddl-auto: none

springdoc:
  api-docs:
    path: /docs-local
    groups:
      enabled: true
  swagger-ui:
    path: /swagger.html
    groups-order: asc
    doc-expansion: none
  cache:
    disabled: true
  model-and-view-allowed: true